Add connect with SSL/TLS
skyhisi/qtmosquitto pull request #1
Opened 2017-05-04 08:19 UTC by marcopellin

Added an overloaded function for doConnect with SSL/TLS certificates.
Added QTDIR in CMakeLists.txt.

2017-05-04 08:56 UTC, skyhisi requested changes

2017-05-04 08:56 UTC, skyhisi commented on README.md
> +    cmake -D CMAKE_BUILD_TYPE=Debug -D QTDIR=/your_home/Qt/5.x/gcc_64/lib/cmake ..\source
This isn't required if the distro provides QT 5, so it shouldn't be in the default instructions.

You could have a "Building on Linux with different QTDIR" section.

2017-05-04 08:56 UTC, skyhisi commented on source/qtmosquitto.cpp
> +    // Connect
This is duplicate code.

It would be better to just add a separate function "configureTls" that you call before the "doConnect".

2017-05-04 09:23 UTC, marcopellin commented on source/qtmosquitto.cpp
> +    // Connect
That's a good idea, thank you.

2019-05-16 11:36 UTC, merged

2019-05-16 11:42 UTC, skyhisi commented
Hi Marco,
Sorry it took me so long to getting around to merging this, I haven't really used this library since I posted it.
Thanks,
Silas